### ISSUE TITLE
Get up to speed with SDL2

### ISSUE THREAD

**Issue by cofogo** [mncookiesstudios/breakout42#7]
Complete SDL2 lessons 1 through 10 [here](http://lazyfoo.net/tutorials/SDL/index.php). This should be sufficient to start coding a simple video game.

**Comment by cofogo** [comment]
60% done.

**Comment by Luke1222** [comment]
OK I am late as always, but I finally started learning things I am supposed
to be learning. THERE ARE QUITE A FEW THINGS that are going wrong. I will
need to solve them by tonight. I wrote the hello world thingie, but it does
not compile, so I am working on that end. Plus the 10 sdl lessons. I've
downloaded the packages it said I need to have I followed the tutorial's
advice when putting them into place. Which did not work, at all,
unsurprisingly. Das ist me, we are talking about. Prepare for A LOT
headaches along the way, sir. Thy teaching patience will be tested.

But I am eager, at the least ;)

**Comment by cofogo** [comment]
Hi,

"It does not compile" is the thing that happens about 99% percent of the
time when an experienced programmer tries to compile a few lines of new
code. For others it happens way more often :D
If you would be more specific, I might be able to help.

As for SDL libraries not working: linking additional libraries correctly
and placing the right version of each file in the right place is more
difficult than it may look, especially if one is not used to doing such
things. (The best way to learn I found was to roll ones sleeves up and
write a dynamically linked library oneself) :D
Did you include the linker flags in the makefile you have written? Or did
you opt to use an IDE?

I will try and call you at about 1700h, if I do not - call me, it is
possible I will have had forgotten... or died or something :)
